// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var App                             = require("./app.js");
var ReactDOMRe                      = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact                     = require("reason-react/lib/js/src/reasonReact.js");
var $dot$slashregisterServiceWorker = require("./registerServiceWorker");

((require('./index.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App.make("Welcome to React and Reason", /* array */[])), "root");

$dot$slashregisterServiceWorker.default();

/*  Not a pure module */
